// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VSRSystemsBackend.Api.Modules.Railway.Infrastructure.Persistence;

#nullable disable

namespace VSRSystemsBackend.Api.Modules.Railway.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(RailwayDbContext))]
    [Migration("20260826102049_AddRailwayInfrastructure")]
    partial class AddRailwayInfrastructure
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VSRSystemsBackend.Api.Modules.Railway.Domain.Shared.RailwayEvidence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Bucket")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("DivisionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("FinalizedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OwnerRecordId")
                        .HasColumnType("uuid");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("ScanDetail")
                        .HasColumnType("text");

                    b.Property<string>("ScanStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset?>("ScannedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "OwnerRecordId");

                    b.HasIndex("ScanStatus", "FinalizedAt");

                    b.ToTable("Evidence", "railway");
                });

            modelBuilder.Entity("VSRSystemsBackend.Api.Modules.Railway.Domain.Shared.RailwayMasterRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid?>("DivisionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("RetiredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "RetiredAt");

                    b.HasIndex("OrganizationId", "DivisionId", "Code")
                        .IsUnique();

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("VSRSystemsBackend.Api.Modules.Railway.Infrastructure.Persistence.RailwayCommandReceipt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uuid");

                    b.Property<long?>("AuthoritativeVersion")
                        .HasColumnType("bigint");

                    b.Property<string>("Code")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("CommandType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid?>("DivisionId")
                        .HasColumnType("uuid");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "UserId", "IdempotencyKey")
                        .IsUnique();

                    b.ToTable("CommandReceipts", "railway");
                });

            modelBuilder.Entity("VSRSystemsBackend.Api.Platform.Outbox.PlatformOutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<Guid?>("CausationId")
                        .HasColumnType("uuid");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset?>("DispatchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset?>("LeaseUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "EventName");

                    b.HasIndex("DispatchedAt", "LeaseUntil", "OccurredAt");

                    b.ToTable("OutboxMessages", "platform");
                });

            modelBuilder.Entity("VSRSystemsBackend.Api.Modules.Railway.Domain.Shared.RailwayAsset", b =>
                {
                    b.HasBaseType("VSRSystemsBackend.Api.Modules.Railway.Domain.Shared.RailwayMasterRecord");

                    b.Property<Guid>("AssetTypeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Criticality")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Point>("Location")
                        .HasColumnType("geometry (point, 4326)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.ToTable("Assets", "railway");
                });

            modelBuilder.Entity("VSRSystemsBackend.Api.Modules.Railway.Domain.Shared.RailwayAssetType", b =>
                {
                    b.HasBaseType("VSRSystemsBackend.Api.Modules.Railway.Domain.Shared.RailwayMasterRecord");

                    b.ToTable("AssetTypes", "railway");
                });

            modelBuilder.Entity("VSRSystemsBackend.Api.Modules.Railway.Domain.Shared.RailwayCorridor", b =>
                {
                    b.HasBaseType("VSRSystemsBackend.Api.Modules.Railway.Domain.Shared.RailwayMasterRecord");

                    b.ToTable("Corridors", "railway");
                });

            modelBuilder.Entity("VSRSystemsBackend.Api.Modules.Railway.Domain.Shared.RailwayDivision", b =>
                {
                    b.HasBaseType("VSRSystemsBackend.Api.Modules.Railway.Domain.Shared.RailwayMasterRecord");

                    b.ToTable("Divisions", "railway");
                });

            modelBuilder.Entity("VSRSystemsBackend.Api.Modules.Railway.Domain.Shared.RailwayPlatform", b =>
                {
                    b.HasBaseType("VSRSystemsBackend.Api.Modules.Railway.Domain.Shared.RailwayMasterRecord");

                    b.Property<Guid>("StationId")
                        .HasColumnType("uuid");

                    b.ToTable("Platforms", "railway");
                });

            modelBuilder.Entity("VSRSystemsBackend.Api.Modules.Railway.Domain.Shared.RailwayRoute", b =>
                {
                    b.HasBaseType("VSRSystemsBackend.Api.Modules.Railway.Domain.Shared.RailwayMasterRecord");

                    b.Property<Guid>("CorridorId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DestinationStationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("OriginStationId")
                        .HasColumnType("uuid");

                    b.ToTable("Routes", "railway");
                });

            modelBuilder.Entity("VSRSystemsBackend.Api.Modules.Railway.Domain.Shared.RailwayStation", b =>
                {
                    b.HasBaseType("VSRSystemsBackend.Api.Modules.Railway.Domain.Shared.RailwayMasterRecord");

                    b.Property<Point>("Location")
                        .HasColumnType("geometry (point, 4326)");

                    b.ToTable("Stations", "railway");
                });

            modelBuilder.Entity("VSRSystemsBackend.Api.Modules.Railway.Domain.Shared.StationZone", b =>
                {
                    b.HasBaseType("VSRSystemsBackend.Api.Modules.Railway.Domain.Shared.RailwayMasterRecord");

                    b.Property<Guid>("StationId")
                        .HasColumnType("uuid");

                    b.ToTable("StationZones", "railway");
                });

            modelBuilder.Entity("VSRSystemsBackend.Api.Modules.Railway.Domain.Shared.TimetableService", b =>
                {
                    b.HasBaseType("VSRSystemsBackend.Api.Modules.Railway.Domain.Shared.RailwayMasterRecord");

                    b.Property<TimeOnly?>("DepartureWindowEnd")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly?>("DepartureWindowStart")
                        .HasColumnType("time without time zone");

                    b.Property<DateTimeOffset>("EffectiveFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("EffectiveTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OperatingStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid?>("PlatformId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RouteId")
                        .HasColumnType("uuid");

                    b.ToTable("TimetableServices", "railway");
                });

            modelBuilder.Entity("VSRSystemsBackend.Api.Modules.Railway.Domain.Shared.TrackSegment", b =>
                {
                    b.HasBaseType("VSRSystemsBackend.Api.Modules.Railway.Domain.Shared.RailwayMasterRecord");

                    b.Property<LineString>("Geometry")
                        .IsRequired()
                        .HasColumnType("geometry (linestring, 4326)");

                    b.ToTable("TrackSegments", "railway");
                });
#pragma warning restore 612, 618
        }
    }
}
