// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VSRSystemsBackend.Api.Modules.Railway.Infrastructure.Persistence;

#nullable disable

namespace VSRSystemsBackend.Api.Modules.Railway.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(RailwayDbContext))]
    [Migration("20260826100712_AddRailwayMasterData")]
    partial class AddRailwayMasterData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VSRSystemsBackend.Api.Modules.Railway.Domain.Shared.RailwayMasterRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid?>("DivisionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("RetiredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "RetiredAt");

                    b.HasIndex("OrganizationId", "DivisionId", "Code")
                        .IsUnique();

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("VSRSystemsBackend.Api.Modules.Railway.Domain.Shared.RailwayAsset", b =>
                {
                    b.HasBaseType("VSRSystemsBackend.Api.Modules.Railway.Domain.Shared.RailwayMasterRecord");

                    b.Property<Guid>("AssetTypeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Criticality")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Point>("Location")
                        .HasColumnType("geometry (point, 4326)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.ToTable("Assets", "railway");
                });

            modelBuilder.Entity("VSRSystemsBackend.Api.Modules.Railway.Domain.Shared.RailwayAssetType", b =>
                {
                    b.HasBaseType("VSRSystemsBackend.Api.Modules.Railway.Domain.Shared.RailwayMasterRecord");

                    b.ToTable("AssetTypes", "railway");
                });

            modelBuilder.Entity("VSRSystemsBackend.Api.Modules.Railway.Domain.Shared.RailwayCorridor", b =>
                {
                    b.HasBaseType("VSRSystemsBackend.Api.Modules.Railway.Domain.Shared.RailwayMasterRecord");

                    b.ToTable("Corridors", "railway");
                });

            modelBuilder.Entity("VSRSystemsBackend.Api.Modules.Railway.Domain.Shared.RailwayDivision", b =>
                {
                    b.HasBaseType("VSRSystemsBackend.Api.Modules.Railway.Domain.Shared.RailwayMasterRecord");

                    b.ToTable("Divisions", "railway");
                });

            modelBuilder.Entity("VSRSystemsBackend.Api.Modules.Railway.Domain.Shared.RailwayPlatform", b =>
                {
                    b.HasBaseType("VSRSystemsBackend.Api.Modules.Railway.Domain.Shared.RailwayMasterRecord");

                    b.Property<Guid>("StationId")
                        .HasColumnType("uuid");

                    b.ToTable("Platforms", "railway");
                });

            modelBuilder.Entity("VSRSystemsBackend.Api.Modules.Railway.Domain.Shared.RailwayRoute", b =>
                {
                    b.HasBaseType("VSRSystemsBackend.Api.Modules.Railway.Domain.Shared.RailwayMasterRecord");

                    b.Property<Guid>("CorridorId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DestinationStationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("OriginStationId")
                        .HasColumnType("uuid");

                    b.ToTable("Routes", "railway");
                });

            modelBuilder.Entity("VSRSystemsBackend.Api.Modules.Railway.Domain.Shared.RailwayStation", b =>
                {
                    b.HasBaseType("VSRSystemsBackend.Api.Modules.Railway.Domain.Shared.RailwayMasterRecord");

                    b.Property<Point>("Location")
                        .HasColumnType("geometry (point, 4326)");

                    b.ToTable("Stations", "railway");
                });

            modelBuilder.Entity("VSRSystemsBackend.Api.Modules.Railway.Domain.Shared.StationZone", b =>
                {
                    b.HasBaseType("VSRSystemsBackend.Api.Modules.Railway.Domain.Shared.RailwayMasterRecord");

                    b.Property<Guid>("StationId")
                        .HasColumnType("uuid");

                    b.ToTable("StationZones", "railway");
                });

            modelBuilder.Entity("VSRSystemsBackend.Api.Modules.Railway.Domain.Shared.TimetableService", b =>
                {
                    b.HasBaseType("VSRSystemsBackend.Api.Modules.Railway.Domain.Shared.RailwayMasterRecord");

                    b.Property<TimeOnly?>("DepartureWindowEnd")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly?>("DepartureWindowStart")
                        .HasColumnType("time without time zone");

                    b.Property<DateTimeOffset>("EffectiveFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("EffectiveTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OperatingStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid?>("PlatformId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RouteId")
                        .HasColumnType("uuid");

                    b.ToTable("TimetableServices", "railway");
                });

            modelBuilder.Entity("VSRSystemsBackend.Api.Modules.Railway.Domain.Shared.TrackSegment", b =>
                {
                    b.HasBaseType("VSRSystemsBackend.Api.Modules.Railway.Domain.Shared.RailwayMasterRecord");

                    b.Property<LineString>("Geometry")
                        .IsRequired()
                        .HasColumnType("geometry (linestring, 4326)");

                    b.ToTable("TrackSegments", "railway");
                });
#pragma warning restore 612, 618
        }
    }
}
