<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\VSRSystemsBackend.Core\VSRSystemsBackend.Core.csproj" />
    <ProjectReference Include="..\VSRSystemsBackend.Shared\VSRSystemsBackend.Shared.csproj" />
  </ItemGroup>

</Project>